gText_Birch_Welcome::
	.string "Greetings!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is James Cokbern.\p"
	.string "But everyone simply calls me the\n"
	.string "Professor.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “Pokémon”.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Mystical, elemental creatures that\n"
	.string "us humans live alongside.\p"
	.string "Though, I'm sure you know that by now,\n"
	.string "hoho!\p"
	.string "However, there is still much we don't\n"
	.string "know about Pokémon.\p"
	.string "That is where I come in-\n"
	.string "I study Pokémon biology. How they do\lwhat they do, and how they're related\lto one another.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "But please, enough about me- tell me\nabout yourself.\p$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "I see.\n"
	.string "And, if you don't mind- your name,\lplease?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}?$"

gText_Birch_YourePlayer::
	.string "A fine name!\p"
	.string "You're moving to Beaston, are you not?\n"
	.string "The heart of the Gagil region, my family\l"
	.string "lives there as well.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "I look forward to seeing you, {PLAYER}!\p"
	.string "Please do stop by my lab, if you get the\nchance.\p"
	.string "I wish you great luck on the adventure\nyou are about to embark on."
	.string "$"
